### PR TITLE
Implementation of Rdf4jUpdateModule

### PR DESCRIPTION
**Pull request by rodionnv**

### CODE REVIEW

**Comment by blcham** [comment]
@rodionnv I guess we can close/remove this pull request right ?

**Comment by blcham** [comment]
@rodionnv I guess this pull request is irrelevant and we can close/remove it, right ?

**Comment by rodionnv** [comment]
@blcham Yes, this one is irrelevant. Correct implementation is in the `rdf4j-update-module` branch.

**Comment by blcham** [comment]
Irrelevant

**Pull request closed without merging**
