### PR TITLE
Refactor RDFNode to string to separate utils class

### LINKED ISSUE #263: Refactor toString method to separate  Utils Class  for converting RDFNode values to the readable string
Screenshot from 2024-08-19 16-21-44

Related to #76 

In ticket #76, the solution addressed only the output for the VariableBindings class. In this ticket, the toString method should be refactored into a separate Utils class so that it can be used in other places.

### PR DESCRIPTION
**Pull request by palagdan**
Resolves #263

### CODE REVIEW

**Comment by blcham** [comment]
@palagdan I am merging this as I understand it only as REFACTORING of code. It does not change any functionality.

**Comment by palagdan** [comment]
@blcham 
I refactored the toString() method to separate it into a utility class and used this method to insert the fields of evidences into the ValidationException map. So it inserts literals in readable form as shown in logs [#76](https://github.com/kbss-cvut/s-pipes/issues/76)

```java                      
  evidenceMap.put(varName, RDFNodeUtils.toString(value));
```

**Comment by blcham** [comment]
@palagdan Ohhhh ... I missed that ... it was misleading that you call this issue refactor. I reserve word refactor to do changes that does not effect functionality.

```
evidenceMap.put(varName, RDFNodeUtils.toString(value));
```

This is not correct way to solve the issue. We do not want to change data that are outputted by RDF, we want to change @context instead.

**Comment by blcham** [comment]
Thus please, revert this line back, while have a look at my proposal at https://github.com/kbss-cvut/s-pipes/issues/265

**Comment by palagdan** [comment]
Sorry, it was a misunderstanding. I thought it would solve the issue with the output of the evidence. Can you tell me how I can revert a line on the remote?

**Pull request merged**
